import { matter } from '@/font'
import type { Metadata } from 'next'
import './globals.css'
import { Figtree } from "next/font/google";
import { cn } from "@/lib/utils";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className={cn("font-sans", figtree.variable)}>
			<body className={`${matter.className} antialiased`}>{children}</body>
		</html>
	)
}
